config/routes.rb
Rails.application.routes.draw do
  resources :barks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "barks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bark.rb
class Bark < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/barks_controller.rb
class BarksController < ApplicationController
  before_action :set_bark, only: %i[ show edit update destroy ]

  # GET /barks or /barks.json
  def index
    @barks = Bark.all.order("created_at DESC")
    @bark = Bark.new
  end

  # GET /barks/1 or /barks/1.json
  def show
  end

  # GET /barks/new
  def new
    @bark = Bark.new
  end

  # GET /barks/1/edit
  def edit
  end

  # POST /barks or /barks.json
  def create
    @bark = Bark.new(bark_params)

    respond_to do |format|
      if @bark.save
        format.html { redirect_to bark_url(@bark), notice: "Bark was successfully created." }
        format.json { render :show, status: :created, location: @bark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barks/1 or /barks/1.json
  def update
    respond_to do |format|
      if @bark.update(bark_params)
        format.html { redirect_to bark_url(@bark), notice: "Bark was successfully updated." }
        format.json { render :show, status: :ok, location: @bark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barks/1 or /barks/1.json
  def destroy
    @bark.destroy

    respond_to do |format|
      format.html { redirect_to barks_url, notice: "Bark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bark
      @bark = Bark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bark_params
      params.require(:bark).permit(:bark)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barks_helper.rb
module BarksHelper
end

app/views/barks/_bark.html.erb
<div id="<%= dom_id bark %>">
  <p>
    <strong>Bark:</strong>
    <%= bark.bark %>
  </p>

</div>

app/views/barks/_feed.html.erb
<div class="column is-half">
  <article class="media box">
    <figure class="media-left">
      <p class="image is-64x64">
        <img src="https://bulma.io/images/placeholders/64x64.png">
      </p>
    </figure>
    <div class="media-content">
      <%= render 'barks/form' %>
    </div>
  </article>


  <% @barks.each do |bark| %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong>Travis Zito</strong><br />
            <small>@TravTheBav</small><br/>
            <p><%= bark.bark %></p>
          </div>
          <div class="level">
            <div class="level-left is-mobile">
              <%= link_to bark, class: "level-item" do %>
                <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
              <% end %>
              <%= link_to edit_bark_path(bark), class: "level-item" do %>
                <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
              <% end %>
              <%= link_to bark, method: :delete, data: { confirm: "Are you sure you want to delete this bark?" } do %>
                <span class="icon"><i class="fa fa-trash" aria-hidden="true"></i></span>
              <% end %>
            </div>
          </div>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/barks/_form.html.erb
<%= simple_form_for(@bark) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :bark, label: "Bark about it", input_html: { class: "textarea" }, wrapper: false,
                       label_html: {class: "label"}, placeholder: "Compose a new bark..." %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/barks/_trends.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Trends</p>
    <a class="panel-block">
      Trend 1
    </a>
    <a class="panel-block">
      Trend 2
    </a>
    <a class="panel-block">
      Trend 3
    </a>
    <a class="panel-block">
      Trend 4
    </a>
    <a class="panel-block">
      Trend 5
    </a>
    <a class="panel-block">
      Trend 6
    </a>
  </nav>
</div>

app/views/barks/_who-to-follow.html.erb
<div class="column">
  <nav class="panel">
    <p class="panel-heading">Who to Follow</p>
  </nav>
  <div class="panel-block">
    <article class="media">
      <div class="media-left">
        <figure class="image is-32x32">
          <img src="https://bulma.io/images/placeholders/64x64.png">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>John Smith</strong>
            <small>@jsmith1</small>
          </p>
        </div>
      </div>
    </article>
  </div>
  <div class="panel-block">
    <article class="media">
      <div class="media-left">
        <figure class="image is-32x32">
          <img src="https://bulma.io/images/placeholders/64x64.png">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>John Smith</strong>
            <small>@jsmith1</small>
          </p>
        </div>
      </div>
    </article>
  </div>
  <div class="panel-block">
    <article class="media">
      <div class="media-left">
        <figure class="image is-32x32">
          <img src="https://bulma.io/images/placeholders/64x64.png">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>John Smith</strong>
            <small>@jsmith1</small>
          </p>
        </div>
      </div>
    </article>
  </div>

</div>

app/views/barks/edit.html.erb
<h1>Editing bark</h1>

<%= render "form", bark: @bark %>

<br>

<div>
  <%= link_to "Show this bark", @bark %> |
  <%= link_to "Back to barks", barks_path %>
</div>

app/views/barks/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render 'trends' %>
      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/barks/new.html.erb
<h1>New bark</h1>

<%= render "form", bark: @bark %>

<br>

<div>
  <%= link_to "Back to barks", barks_path %>
</div>

app/views/barks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bark %>

<div>
  <%= link_to "Edit this bark", edit_bark_path(@bark) %> |
  <%= link_to "Back to barks", barks_path %>

  <%= button_to "Destroy this bark", @bark, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice]%>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-info">
      <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-5">Barker</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div class="navbarExample navbar-menu">
      <div class="navbar-end">
        <div class="field is-grouped">
          <p class="control">
            <%= link_to 'New Bark', new_bark_path, class: "button is-info is-inverted" %>
          </p>
        </div>
      </div>
    </div>
      
    </nav>

    <%= yield %>
  </body>
</html>